### ISSUE TITLE
Support for polymorphic collections. Not like in backbone.

### ISSUE THREAD

**Issue by far-blue** [Volicon/NestedTypes#119]
As the decision has been made to stick with Backbone 1.1.x 'forever', what is the plan for various bug fixes and enhancements that were added in 1.2.x? Will they be back ported?
For instance, 1.1.x has a bug where you can't use a custom attribute for a model's uid in a collection if you supply a factory function for the model definition (rather than a constructor function). This is fixed in 1.2.x with the modelId attribute on the collection which can be a function.

**Comment by gaperton** [comment]
Look, the situation is like this.

For the Models, NestedTypes currently overrides [almost] everything and doesn't use any important part of Backbone code. Completely different implementation, that's why it is 40 times faster.

For Collections, it currently still uses Backbone base class, but overrides a lot of things including constructor, so it started to be painful to maintain compatibility with different backbone versions.It appears that 1.2 changes brake a lot of things in NestedTypes, and it's not trivial to make it work with 1.2 and 1.1 at the same time.

As fast solution, I bundled 1.1.2 which is known to be very stable in our product. A bit later, I'm going to upgrade it to 1.2.X fixing integration bugs, and/or deeply refactor their Collections (taking 1.2 features into account), to make them faster. Not sure yet, will I do first, second, or both. Likely, the both. Though it's not easy, but I'm pretty sure that I can make much better Collections than backbone currently have.

**Comment by far-blue** [comment]
Sounds very reasonable to me :) I only pushed for clarification because we have every intention of basing large quantities of code expected to have a 4 or 5 year lifespan on the NestedTypes codebase :) We are very keen on using NestedTypes but we can't really adopt it so heavily without some understanding of where the codebase is going next. I'd have no problems with NestedTypes going like LowDash - being compatible with but not actually sharing much code with Underscore. My only concerns about Backbone v1.2.x are based on personal experience of the bugs in v1.1.x.

**Comment by gaperton** [comment]
>  if you supply a factory function for the model definition

You mean this?
```
var Library = Backbone.Collection.extend({

  model: function(attrs, options) {
    if (condition) {
      return new PublicDocument(attrs, options);
    } else {
      return new PrivateDocument(attrs, options);
    }
  }
});
```

Having polymorphic collections is important feature, but I completely not sure that it's good idea to throw out information about type in favor of factory function. I would say, it's crappy idea. We need both. I would rather design alternative mechanics for that.

**Comment by gaperton** [comment]
IMHO, it makes more sense to attach factory function to the Model constructor. In this case, when Collection is configured to hold an abstract model, it will use factory function. So, it will look like this:

```javascript
var AbstractModel = Model.extend({

},{
    create : function( attrs ){
        return new modelType[ attrs.type ];
    }
});

var modelType = {
   first : FirstModel,
   second : SecondModel
}

// Then, just create your collection.
var c = new AbstractModel.Collection();
```

This is the direction I will think when I will support this feature.

**Comment by far-blue** [comment]
The problem in Backbone was simply that Backbone assumed if the model attribute was not a constructor function that it was an object that had an attribute of idAttribute. If you supplied a factory function instead, allowing for a heterogeneous collection, then the idAttribute wouldn't exist and so you were unable to change the attribute used for the id on the models created by the factory and had to use 'id'. I got around this by specifically adding the idAttribute value to the prototype of the factory function (rather a hack) but in Backbone 1.2.x they added a modelId attribute on the collection, fixing the problem.

When I'm back in the office tomorrow I'll gist some code so you can see what I mean :)

To be clear, I wasn't trying to create a heterogeneous collection where each Model has a different attribute as the idAttribute, just that I wanted a Collection of Models (all subclasses of a base Model) where they all had an idAttribute of 'uid' instead of 'id'.

**Comment by far-blue** [comment]
The Backbone docs explain the more extreme case of a heterogeneous set of Models where each type of Model might have a different idAttribute:
http://backbonejs.org/#Collection-modelId

**Comment by far-blue** [comment]
Here's a gist of some code we wrote where we had to find a work-around for the combination of model factory and model custom id attribute in Backbone 1.1.2
https://gist.github.com/far-blue/bd85dfa7349fd3665645#file-models-js

**Comment by gaperton** [comment]
Yes, I understand. I really don't like an idea of placing model factory instead of model type. It will break a lot of things, for example, automatic collection declarations.

Currently, most of the time you don't declare collections in NestedTypes. Every model has Collection, so you do YourModel.Collection and that's it. To support automatic declaration of polymorphic collections, we need to add factory to model definition, and directly support abstract models with attached factories. Something like that I have shown in upper comment.

**Comment by gaperton** [comment]
And that's why I like tickets. They trigger imagination. No, in this particular case it won't be compatible with backbone. I would rather provide different way of doing polymorphic stuff. Solving polymorphic model attribute and collection at the same time, with a same technique. I mean, why the hell you need to create the factory for the same type twice.

**Comment by far-blue** [comment]
It would be good if there was a way to define, on the Model, that a factory should be used when instantiating. That way you'd not have to setup the factory on each other model that uses it as an instance and you could maybe do something automatic with the collection as well.

**Comment by gaperton** [comment]
Usually, it looks like this. You have base class for an abstract Model, lets call it DashboardWidgetModel to be specific.

Then, you have multiple widgets definitions, may be in separate files. All of them require DashboardWidgetModel and extending it.

Then, you need a factory to successfully deserialize DashboardWidgetModel. For that, will be enough to attach 'create' factory function to the DashboardWidgetModel constructor, but you can't do it right inside of its definition, cause, if you use modules you will get circular require. Therefore, somewhere in a side, you need to require all Widget modules, and do DashboardWidgetModel.create = function( attrs ){ ... }.

Single factory attached to an abstract class. That's it. After that, both DashboardWidgetModel.Collection and nested DashboardWidgetModel will work just fine. In next NestedTypes version, of course, currently it doesn't work.

That's the solution for this bug I would prefer. So, generally, the difference is that (1) you need to have common base class for the models belonging to collection, and (2) you move factory to that base class.

**Comment by far-blue** [comment]
That sounds great to me :)

**Comment by far-blue** [comment]
We have just this moment hit another place in our code where the create() factory concept would be a perfect fit so I'm really looking forward to seeing this implemented :)

**Comment by gaperton** [comment]
On this week, I think.

**Comment by gaperton** [comment]
fixed in 1.3rc

**Comment by gaperton** [comment]
Completely new collections core inside, by the way. In average, 5 times faster in every browser.

**Comment by far-blue** [comment]
This sounds great and we look forward to playing with it all when it is released :)

**Comment by gaperton** [comment]
Done, implemented exactly as discussed here.

Any model with static `create( attrs, options )` factory function is an abstract polymorphic model, so it will just work no matter where will you use its type. Its implicit collection will be polymorphic to.
