### ISSUE TITLE
"invalid" event not fired

### ISSUE THREAD

**Issue by Bolik** [Volicon/NestedTypes#149]
Hi, 

i wrote simple model with validate function:

ProfileChangePasswordModel = Nested.Model.extend({

    attributes: {
        password: String.value( null ).has.toJSON( false ),
        new_password: String.value( null),
        new_password2: String.value( null ).has.toJSON( false )
    },

    validate (attrs) {
        if (!!!attrs.password) {
            console.log('1');
            return _('Password required message');
        }
        if (!!!attrs.new_password) {
            console.log('2');
            return _('New password required message');
        }
        if (attrs.new_password != attrs.new_password2) {
            console.log('3');
            return _('Passwords are not equal message');
        }
    }
}

After execute model.isValid() "1" printed but "invalid" event never triggered

**Comment by gaperton** [comment]
Yes, it's currently fired only from within model.save. Because validation is done significantly different, and the semantic of this event is not clear.

How should it behave on object tree, for instance? Should these events bubble up? If yes, how many events should appear at the top of the tree if there are many errors inside?

In NestedTypes, validation result is cached across the tree. It means, that no matter how many times isValid is called, validation will happen once, until model will be changed. Speaking of invalid event - should it be thrown every time isValid is called, or just once?

How it's being used, what is the purpose?

**Comment by Bolik** [comment]
I've tried to override validate method and get validationerror

**Comment by gaperton** [comment]
That should work. Error returned from local validate can be obtained through `model.validationError.error`. Since validation is generalized on object tree, structure of validationError is different when compared to backbone. It holds children errors tree.

https://github.com/Volicon/Type-R/blob/master/src/validation.ts

`validationError` is lazily evaluated (and cached) for both models and collections, so you can just access it directly. Just `model.validationError` - and validation will instantly happen, if it didn't before. 

And there's an alternative way of writing this validation in your example.

```
attributes: {
    password: String.value( null ).has.toJSON( false )
                                                     .check( x => x,  _('Password required message') ),
    new_password: String.value( null).has
                                                     .check( x => x,  _('New password required message') ),
    new_password2: String.value( null ).has.toJSON( false )
                                    .check( function( x ){ return x === this.new_password },  _('Passwords must be equal') )
}
```

Advantage of this approach is that you'll get all errors at once. So, you can display them on you form all at once (inlined in your controls). 

There are no 'invalid' event everywhere, though. Just in `save. I can implement it if I understand its semantic on object trees, and scenarios ho it's used.

**Comment by gaperton** [comment]
That's some notes on how validation works. http://slides.com/vladbalin/deck#/

**Comment by Bolik** [comment]
Thanks, there is a lot of useful info. But your alternatives check doesn't work with nestedtypes 1.3.1. What is the latest stable version?

**Comment by gaperton** [comment]
has.check should work with 1.3. It's the way how all validation is made in
our product.

вт, 9 авг. 2016 г. в 6:26, Alexey Slynko <notifications@github.com>:
