### ISSUE TITLE
has.set for nested model

### ISSUE THREAD

**Issue by Bolik** [Volicon/NestedTypes#150]
Hi, 

i wish to change set method for nested model. Example:

const Test = Nested.Model.extend({
 title: String.has.set( function (value, name) { console.log('this happens'); }),
struct: Nested.Model.extend({
    a: Number
}).has.set( function (value, name) { console.log('this never happens'); })
});

let a = new Test();
a.struct = '12345'; // struct.set never called

What's wrong?

**Comment by gaperton** [comment]
First, change is these examples is being rejected, because set hook returns 'undefined'.

Second, you have to wrap attribute definitions in 'attributes' or 'defaults' object. Or, use `Model.defaults` instead of `Model.extend`.

`Model.defaults( attrSpec )` is an equivalent of `Model.extend({ defaults : attrSpec })`. Used for inline models definitions.

```javascript
const Test = Nested.Model.defaults({
title: String.has.set( function (value, name) { console.log('this happens'); }),
struct: Nested.Model.defaults({
a: Number
}).has.set( function (value, name) { console.log('this never happens'); })
});
```

**Comment by gaperton** [comment]
Also, there's an important detail about `set` hook. It executed only when an attribute's value is being changed, not when something inside of the structure is changed. It happens _before_ the actual change, and gives you an opportunity to _change_ the value before it will be set.

And when it's called, assigned value is being converted to the attribute type. You're assigning the string to the attribute with model type. Obviously, it can't be converted to the model, as type is incompatible. In this case, it will be delegated to `a.struct.set( '12345' )` for the chance it's an object hash (so, `a.struct` value is not changed as there's an attempt to update struct in place, and no `set` hook is being called).  But since the value is the string, nothing will happen, but you will receive an error in the console. Something about string is not an object hash.

**Comment by Bolik** [comment]
Thanks a lot

**Comment by gaperton** [comment]
If your intention is not to alter the value before it's being set (which is very rarely needed), it's better to use 'change:struct' listener. That's what we're doing the most of the time.

These events happens _after_ update, and any additional changes made in event handlers won't trigger any additional model 'change' events (and won't cause additional renders) as they are executed in the scope of the current transaction.

```javascript
const Test = Nested.Model.defaults({
    title: String,
    struct: Nested.Model.defaults({
        a: Number
    })

    initialize : function(){
        this.listenTo( this, {
            'change:title' : function(){ ... },
            'change:struct' : function(){ ... }
        }
    }
});
```

**Comment by gaperton** [comment]
In 2.0 beta (which is mostly functional now), you can use `.has.watcher` to subscribe for 'change:attr':

It might work in 1.3 as well, but I'm not really sure.

```javascript
const Test = Nested.Model.defaults({
    title: String.has.watcher( function (value, name) { console.log('this happens'); }),
    struct: Nested.Model.defaults({
        a: Number
    }).has.watcher( function (value, name) { console.log('this never happens'); })
});
```
